version: '3'
services:
  
  server:
    build: my-nginx/.
    ports:
      - "8081:8081"

  webapp:
    build: my-app/.

    ports:
      - "10086:10086"
 
    depends_on:
      - "db"

  db:
    image: daocloud.io/library/mysql:5.7.4

    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=yelda
      # - "DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;"
