version: '3'
services:
  
  frontend:
    image: 15331335/yelda_app:v1

    volumes:
      - ./conf.d/:/etc/nginx/conf.d

    ports:
      - "8080:8080"

  backend:
    image: jarvisw/yelda_webapp:v1

    volumes:
      - ./instance/:/www/instance

    ports:
      - "10086:10086"
  
    depends_on:
      - "db"

  db:
    image: daocloud.io/library/mysql:5.7.4

    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=yelda
