SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE Images;
TRUNCATE TABLE Jobs;
TRUNCATE TABLE Labels;
TRUNCATE TABLE AgeDMEChoice;
TRUNCATE TABLE HRChoice;
TRUNCATE TABLE ImageStageChoice;
TRUNCATE TABLE Accounts;
SET FOREIGN_KEY_CHECKS = 1;
