SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE Images;
DROP TABLE Jobs;
DROP TABLE Labels;
DROP TABLE AgeDMEChoice;
DROP TABLE HRChoice;
DROP TABLE ImageStageChoice;
DROP TABLE Accounts;
SET FOREIGN_KEY_CHECKS = 1;
